# Site settings
title: "  Razor Variables"
header-img: img/home-bg.jpg
email: jduarte@caltech.edu
copyright_name: Caltech
description: "Information about razor variables for experimental high energy physics"
baseurl: "/startbootstrap-clean-blog-jekyll"
#baseurl: ""
url: "http://yourdomain.com"
github_username:  RazorCMS/RazorVariables
#email_username:  jduarte@caltech.edu

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed, 'jekyll/scholar']

scholar:
  style: apa
  locale: en
  bibliography: bibliography.bib
  sort_by: year,month
  order: ascending
  source: ./
  bibliography_template: bib